name: Install dependencies

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '22'
    - name: Install dependencies
      run: npm install --global yarn && yarn
      shell: bash
