name: Lint

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Format
      run: npm run format
      shell: bash
    - name: Lint
      run: npm run lint
      shell: bash
