name: Lint

runs:
  using: 'composite'
  steps:
    # - uses: actions/checkout@v3
    - name: Format
      run: npm run format:check
      shell: bash
    - name: Lint
      run: npm run lint
      shell: bash
