name: PR

# on: [pull_request]
on: [push]

jobs:
  # lint:
  #   name: Lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: ./.github/actions/lint
  build:
    name: Deploy
    runs-on: ubuntu-latest
    # needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install --global yarn && yarn
        shell: bash
      - name: Build
        run: yarn && yarn build
        shell: bash
      - name: Publish
        id: publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --build # https://github.com/netlify/netlify-plugin-nextjs#deploying
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      - name: Live URL
        run: echo ${{ steps.publish.outputs.NETLIFY_OUTPUT }} ${{ steps.publish.outputs.NETLIFY_URL }} ${{ steps.publish.outputs.NETLIFY_LIVE_URL }}
